### ISSUE TITLE
fetch and 302 redirects and POST

### ISSUE THREAD

**Issue by dbouwman** [Esri/torii-provider-arcgis#51]
In debugging an issue with Portal, the backing system was setup so that http requests to the api would be 302'd to https requests.

It seems like `fetch` would follow the 302, but was not smart enough to send the same body if the first request was a POST. Rather, it would send a GET, w/o the `f=json&token=34b2js...` and that would return the html, which would 💣 the app.

I propose we change that call to force a GET --> `return arcgisRest.request(userUrl, { authentication: authMgr, httpMethod: 'GET' });`

Still checking if this is a Portal/Enterprise thing, or something unique to this one env. If the latter, we may not need this, but should still consider looking into why the 302 is respected, but the form is not re-sent.

**Comment by jgravois** [comment]
I can make this change and swap in ember-fetch at the same time.

**Comment by tomwayson** [comment]
resolved in #52
